BookStore/Controllers/HomeController.cs
using BookStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class HomeController : BaseController
    {
        private int unitsInPage = 10;
        public ActionResult Contact()
        {
            ViewBag.Message = "Контактные данные";

            return View();
        }

        public ActionResult Users()
        {
            ViewBag.Message = "Пользователи";
            var users = _context.GetReviews();
            return View(users);
        }

        public ActionResult CreateBook()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateBook(Book book)
        {
            if (ModelState.IsValid)
            {
                _context.AddBook(book);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CreateBook", "Something wrong!");
            }
            return View(book);
        }

        public ActionResult DetailsBook(int Id = 1)
        {
            var book = _context.GetBook(Id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        public ActionResult EditBook(int Id)
        {
            var book = _context.GetBook(Id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        [HttpPost]
        public ActionResult EditBook(Book book)
        {
            if (ModelState.IsValid)
            {
                _context.Update(book);
                return RedirectToAction("DetailsBook", "Home", new { id = book.Id });
            }
            else
            {
                ModelState.AddModelError("EditBook", "Something wrong!");
            }
            return View(book);
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult Index(int? id)
        {
            int page = id ?? 0;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_Items", GetItemsPage(page));
            }
            return View(GetItemsPage(page));
        }

        private List<Book> GetItemsPage(int page = 1)
        {
            var itemsToSkip = page * unitsInPage;

            return _context.GetBooks().OrderBy(t => t.Id).Skip(itemsToSkip).
                Take(unitsInPage).ToList();
        }
    }
}

BookStore/Controllers/ReviewController.cs
using BookStore.Models;
using System.Linq;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    public class ReviewController : BaseController
    { 
        public ActionResult Create(int bookId, string name)
        {
            var review = new BookReview() { BookId = bookId, Name = name };
            return View(review);
        }

        [HttpPost]
        public ActionResult Create(BookReview newReview)
        {
            if (ModelState.IsValid)
            {
                var errors = ModelState.SelectMany(x => x.Value.Errors.Select(z => z.Exception));
                _context.AddReview(newReview);
                return RedirectToAction("DetailsBook", "Home", new { id = newReview.BookId });
            }
            else
            {
                ModelState.AddModelError("Create", "Something wrong!");
            }
            return View(newReview);
        }

        [HttpPost]
        public void AddReport(int reviewId, string reason)
        {
            var review = _context.GetReview(reviewId);
            if (review == null)
            {
                Response.StatusCode = 404;
                return;
            }

            review.IsOffensive = true;
            review.ReportReason = reason;
            _context.Update(review); 
        }

        [HttpPost]
        public int AddLike(int reviewId)
        {
            var review = _context.GetReview(reviewId);
            if (review == null)
            {
                Response.StatusCode = 404;
                return -1;
            }

            ++review.Likes;
            _context.Update(review);

            return review.Likes;
        }
    }
}

BookStore/Views/Home/Contact.cshtml
<h2>@ViewBag.Message</h2>

<address>
    ул. Союзная, 144а<br />
    Ярославль, Ярославская область<br />
    <abbr title="Phone">P:</abbr>
    +7 (4852) 55-66-44
</address>

<address>
    <span class="fa fa-at" aria-hidden="true"/> <strong>Поодержка:</strong>   <a href="mailto:buzanovn@gmail.com">buzanovn@gmail.com</a><br />
    <span class="fa fa-vk" aria-hidden="true" /> <strong>VK:</strong> <a href="http://vk.com/buzanovn">buzanovn</a><br />
    <span class="fa fa-telegram" aria-hidden="true" /> <strong>Telegram</strong> <a href="http://t.me/buzanovn">buzanovn</a>
</address>

BookStore/Views/Home/CreateBook.cshtml
@model BookStore.Models.Book

@{
    ViewBag.Title = "CreateBook";
}

<h2>Добавить Книгу</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-primary" />
                @Html.ActionLink("Назад", "Index", null, htmlAttributes: new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<div>
    
</div>

BookStore/Views/Home/DetailsBook.cshtml
@model BookStore.Models.Book

@{
    ViewBag.Title = "DetailsBook";
}

<h2>Подробней о книге</h2>
<hr />
<div class="jumbotron">
    <dl class="dl-horizontal">
        <dt> @Html.DisplayNameFor(model => model.Author) </dt>
        <dd> @Html.DisplayFor(model => model.Author) </dd>
        <dt> @Html.DisplayNameFor(model => model.Name) </dt>
        <dd> @Html.DisplayFor(model => model.Name) </dd>
        <dt> @Html.DisplayNameFor(model => model.Genre) </dt>
        <dd> @Html.DisplayFor(model => model.Genre) </dd>
    </dl>
    @Html.ActionLink("Редактировать", "EditBook", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
    @Html.ActionLink("Добавить отзыв", "Create", "Review", new { BookId = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
    @Html.ActionLink("Назад", "Index", null, htmlAttributes: new { @class = "btn btn-secondary" })
</div>
<h2>Отзывы</h2>
<hr />
@Html.Partial("ReviewPartial", new BookStore.Controllers.BaseController()._context.GetReviews(Model.Id))

BookStore/Views/Home/EditBook.cshtml
@model BookStore.Models.Book

@{
    ViewBag.Title = "EditBook";
}

<h2>Редактировать Книгу</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.DisplayFor(model => model.FullName)
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                @Html.ActionLink("Назад", "Index", null, htmlAttributes: new { @class = "btn btn-secondary" })
            </div>
        </div>
    </div>
}

BookStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@model  IEnumerable<BookStore.Models.Book>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="scrolList">
    @Html.Partial("_Items")
</div>

<div id="loading" style="text-align: center">
    <img src='@Url.Content("~/Content/loading_spinner.gif")'>
</div>

@Scripts.Render("~/bundles/infinitescroll")

BookStore/Views/Home/Users.cshtml
@model IEnumerable<BookStore.Models.BookReview>

@{
    ViewBag.Title = "Users";
}

<h2>Пользователи</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Review)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReportReason)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReportReason)
            </td>
        </tr>
    }

</table>

BookStore/Views/Home/_Items.cshtml
@model IEnumerable<BookStore.Models.Book>
@foreach (var book in Model)
{
    <div class="card">
        <div class="card-header">
            <h2 class="card-title"> @book.Name </h2>
        </div>
        <div class="card-block">
            <p class="card-text"> <b>Жанр</b>: @book.Genre </p>
            <p class="card-text"> <b>Автор</b>: @book.Author </p>
            @Html.ActionLink("Подробнее", "DetailsBook", new { id = book.Id }, htmlAttributes: new { @class = "card-link btn btn-primary" })
        </div>
    </div>
}